server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka
  instance:
    prefer-ip-address: true
    instance-id: springcloud-gateway
spring:
  application:
    name: springcloud-gateway
